/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// NamespaceQueueApplyConfiguration represents a declarative configuration of the NamespaceQueue type for use with apply.
type NamespaceQueueApplyConfiguration struct {
	v1.TypeMetaApplyConfiguration    `json:",inline"`
	*v1.ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
	Spec                             *QueueSpecApplyConfiguration   `json:"spec,omitempty"`
	Status                           *QueueStatusApplyConfiguration `json:"status,omitempty"`
}

// NamespaceQueue constructs a declarative configuration of the NamespaceQueue type for use with apply.
func NamespaceQueue(name, namespace string) *NamespaceQueueApplyConfiguration {
	b := &NamespaceQueueApplyConfiguration{}
	b.WithName(name)
	b.WithNamespace(namespace)
	b.WithKind("NamespaceQueue")
	b.WithAPIVersion("scheduling.volcano.sh/v1beta1")
	return b
}

func (b NamespaceQueueApplyConfiguration) IsApplyConfiguration() {}

func (b *NamespaceQueueApplyConfiguration) WithKind(value string) *NamespaceQueueApplyConfiguration {
	b.TypeMetaApplyConfiguration.Kind = &value
	return b
}

func (b *NamespaceQueueApplyConfiguration) WithAPIVersion(value string) *NamespaceQueueApplyConfiguration {
	b.TypeMetaApplyConfiguration.APIVersion = &value
	return b
}

func (b *NamespaceQueueApplyConfiguration) ensureObjectMetaApplyConfigurationExists() {
	if b.ObjectMetaApplyConfiguration == nil {
		b.ObjectMetaApplyConfiguration = &v1.ObjectMetaApplyConfiguration{}
	}
}

func (b *NamespaceQueueApplyConfiguration) WithName(value string) *NamespaceQueueApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Name = &value
	return b
}

func (b *NamespaceQueueApplyConfiguration) WithNamespace(value string) *NamespaceQueueApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Namespace = &value
	return b
}

func (b *NamespaceQueueApplyConfiguration) WithGenerateName(value string) *NamespaceQueueApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.GenerateName = &value
	return b
}

func (b *NamespaceQueueApplyConfiguration) WithUID(value types.UID) *NamespaceQueueApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.UID = &value
	return b
}

func (b *NamespaceQueueApplyConfiguration) WithResourceVersion(value string) *NamespaceQueueApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.ResourceVersion = &value
	return b
}

func (b *NamespaceQueueApplyConfiguration) WithGeneration(value int64) *NamespaceQueueApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Generation = &value
	return b
}

func (b *NamespaceQueueApplyConfiguration) WithCreationTimestamp(value metav1.Time) *NamespaceQueueApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.CreationTimestamp = &value
	return b
}

func (b *NamespaceQueueApplyConfiguration) WithDeletionTimestamp(value metav1.Time) *NamespaceQueueApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionTimestamp = &value
	return b
}

func (b *NamespaceQueueApplyConfiguration) WithDeletionGracePeriodSeconds(value int64) *NamespaceQueueApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionGracePeriodSeconds = &value
	return b
}

func (b *NamespaceQueueApplyConfiguration) WithLabels(entries map[string]string) *NamespaceQueueApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Labels == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Labels[k] = v
	}
	return b
}

func (b *NamespaceQueueApplyConfiguration) WithAnnotations(entries map[string]string) *NamespaceQueueApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Annotations == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Annotations[k] = v
	}
	return b
}

func (b *NamespaceQueueApplyConfiguration) WithOwnerReferences(values ...*v1.OwnerReferenceApplyConfiguration) *NamespaceQueueApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOwnerReferences")
		}
		b.ObjectMetaApplyConfiguration.OwnerReferences = append(b.ObjectMetaApplyConfiguration.OwnerReferences, *values[i])
	}
	return b
}

func (b *NamespaceQueueApplyConfiguration) WithFinalizers(values ...string) *NamespaceQueueApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		b.ObjectMetaApplyConfiguration.Finalizers = append(b.ObjectMetaApplyConfiguration.Finalizers, values[i])
	}
	return b
}

func (b *NamespaceQueueApplyConfiguration) WithSpec(value *QueueSpecApplyConfiguration) *NamespaceQueueApplyConfiguration {
	b.Spec = value
	return b
}

func (b *NamespaceQueueApplyConfiguration) WithStatus(value *QueueStatusApplyConfiguration) *NamespaceQueueApplyConfiguration {
	b.Status = value
	return b
}
