/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	apisschedulingv1beta1 "volcano.sh/apis/pkg/apis/scheduling/v1beta1"
	versioned "volcano.sh/apis/pkg/client/clientset/versioned"
	internalinterfaces "volcano.sh/apis/pkg/client/informers/externalversions/internalinterfaces"
	schedulingv1beta1 "volcano.sh/apis/pkg/client/listers/scheduling/v1beta1"
)

// NamespaceQueueInformer provides access to a shared informer and lister for
// NamespaceQueues.
type NamespaceQueueInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() schedulingv1beta1.NamespaceQueueLister
}

type namespaceQueueInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewNamespaceQueueInformer constructs a new informer for NamespaceQueue type.
func NewNamespaceQueueInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredNamespaceQueueInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredNamespaceQueueInformer constructs a new informer for NamespaceQueue type.
func NewFilteredNamespaceQueueInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SchedulingV1beta1().NamespaceQueues(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SchedulingV1beta1().NamespaceQueues(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SchedulingV1beta1().NamespaceQueues(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SchedulingV1beta1().NamespaceQueues(namespace).Watch(ctx, options)
			},
		}, client),
		&apisschedulingv1beta1.NamespaceQueue{},
		resyncPeriod,
		indexers,
	)
}

func (f *namespaceQueueInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredNamespaceQueueInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *namespaceQueueInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisschedulingv1beta1.NamespaceQueue{}, f.defaultInformer)
}

func (f *namespaceQueueInformer) Lister() schedulingv1beta1.NamespaceQueueLister {
	return schedulingv1beta1.NewNamespaceQueueLister(f.Informer().GetIndexer())
}
